@extends('layouts.app')
@section('title', 'PPT Department Applications')
@section('main_content')
<div class="content-body default-height"><div class="container-fluid">
  <div class="row page-titles"><div class="col-lg-6"><ol class="breadcrumb"><li class="breadcrumb-item active"><a href="javascript:void(0)">PPT Department — Online Domain</a></li></ol></div><div class="col-lg-6 text-end"><a href="{{ route('ppt-department.step', 1) }}" class="btn btn-rounded btn-info"><span class="btn-icon-start text-info"><i class="fa fa-plus color-info"></i></span>New PPT Application</a></div></div>
  <div class="row"><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-primary text-primary"><i class="fa fa-folder-open fa-2x"></i></span><div class="media-body"><p class="mb-1">Total Applications</p><h4 class="mb-0">42</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-warning text-warning"><i class="fa fa-hourglass-half fa-2x"></i></span><div class="media-body"><p class="mb-1">Under Validation</p><h4 class="mb-0">09</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-success text-success"><i class="fa fa-check-circle fa-2x"></i></span><div class="media-body"><p class="mb-1">Approved</p><h4 class="mb-0">27</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-danger text-danger"><i class="fa fa-archive fa-2x"></i></span><div class="media-body"><p class="mb-1">Archived</p><h4 class="mb-0">06</h4></div></div></div></div></div></div>
  <div class="card"><div class="card-header"><h4 class="card-title mb-0">PPT Department Applications</h4></div><div class="card-body"><div class="table-responsive"><table id="example10" class="display" style="width:100%"><thead><tr><th>S No</th><th>Application No.</th><th>Client Name</th><th>District</th><th>Mineral</th><th>Folders</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>@php($applications=[['PPT-2026-0042','M. Senthil Kumar','Salem','Granite','11 / 11','Approved','06 Aug 2026'],['PPT-2026-0041','S. Priya','Erode','Rough Stone','09 / 11','Validation','05 Aug 2026'],['PPT-2026-0040','K. Rajendran','Madurai','Gravel','11 / 11','Archived','02 Aug 2026'],['PPT-2026-0039','V. Karthik','Coimbatore','Lime Stone','05 / 11','Document Preparation','01 Aug 2026']])@foreach($applications as [$number,$client,$district,$mineral,$folders,$status,$updated])<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $number }}</strong></td><td>{{ $client }}</td><td>{{ $district }}</td><td>{{ $mineral }}</td><td><a href="{{ route('ppt-department.step', 4) }}">{{ $folders }} folders</a></td><td><span class="badge badge-{{ $status === 'Approved' ? 'success' : ($status === 'Archived' ? 'secondary' : ($status === 'Validation' ? 'warning' : 'primary')) }}">{{ $status }}</span></td><td>{{ $updated }}</td><td><a href="{{ route('ppt-department.step', $status === 'Document Preparation' ? 4 : 6) }}" class="btn btn-sm btn-primary">View</a></td></tr>@endforeach</tbody></table></div></div></div>
</div></div>
@endsection
