@extends('layouts.app')
@section('title', 'PPT Department Workflow')
@section('main_content')
<link href="{{ asset('css/style1.css') }}" rel="stylesheet">
@php($labels=['Client','District','Minerals','Folders','Documents','Approval','Preview'])
@php($folders=[['Documents','PARIVESH online uploading documents','fa-file-alt'],['EDS & EDS Reply','EDS and EDS reply','fa-comments'],['Demand Note','SPCB payment receipt and comments','fa-file-invoice-dollar'],['File No','Schedule, PPT, Radius KML, NOC and CER','fa-folder-open'],['SEAC Agenda','SEAC agenda','fa-users'],['SEAC Minutes','ADS and ADS reply if any','fa-clipboard-list'],['ADS','ADS reply documents and PPT','fa-file-alt'],['CER Affidavit','CER affidavit','fa-balance-scale'],['SEIAA Agenda','SEIAA agenda','fa-users'],['SEIAA Minutes','ADS and ADS reply if any','fa-clipboard-check'],['Environmental Clearance','Environmental clearance','fa-leaf']])
<div class="content-body default-height"><div class="container-fluid"><div class="wizard-wrap" style="max-width:920px;"><div class="step-progress">@foreach($labels as $number => $label)<div class="sp-step {{ $number + 1 < $step ? 'done' : ($number + 1 === $step ? 'active' : '') }}"><div class="circ">@if($number + 1 < $step)<i class="bi bi-check-lg"></i>@else{{ $number + 1 }}@endif</div><div class="sp-label">{{ $label }}</div></div>@endforeach</div><div class="wizard-card"><div class="wc-eyebrow">Step {{ $step }} of 7 &middot; PPT Department Online Domain</div>
@if($step===1)<h4>Client Name</h4><div class="wc-sub">Start the PPT Department process with client and project details.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Client Name *</label><input class="form-control" placeholder="Applicant name"></div><div class="col-md-6"><label class="form-label">Project / Quarry Name *</label><input class="form-control" placeholder="Project name"></div><div class="col-md-6"><label class="form-label">Mobile Number *</label><input class="form-control" placeholder="10-digit mobile number"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" placeholder="name@example.com"></div></div>
@elseif($step===2)<h4>District Wise Details</h4><div class="wc-sub">Select the district where the mining project is located.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">District *</label><select class="form-select"><option>Select district</option><option>Coimbatore</option><option>Salem</option><option>Madurai</option><option>Erode</option></select></div><div class="col-md-6"><label class="form-label">Taluk / Village</label><input class="form-control" placeholder="Taluk or village"></div></div>
@elseif($step===3)<h4>Mineral Details</h4><div class="wc-sub">Select the mineral type to continue with the PPT document structure.</div><div class="row g-2">@foreach(['Rough Stone','Gravel','Granite','Lime Stone','Fire Clay','Others'] as $mineral)<div class="col-md-6"><div class="opt-tile {{ $loop->first ? 'selected' : '' }}"><div class="opt-radio"></div><div><div class="opt-title">{{ $mineral }}</div><div class="opt-desc">Mineral category</div></div></div></div>@endforeach</div>
@elseif($step===4)<h4>PPT Department Folders</h4><div class="wc-sub">The process is organised into eleven folders. Select a folder to prepare its documents.</div><div class="row g-3">@foreach($folders as [$name,$detail,$icon])<div class="col-md-4"><div class="folder-tile"><div class="fico"><i class="fa {{ $icon }}"></i></div><div class="ftitle">{{ $loop->iteration }}. {{ $name }}</div><div class="fmeta">{{ $detail }}</div><span class="badge-status pending">Not started</span></div></div>@endforeach</div>
@elseif($step===5)<h4>Upload & Validate Data</h4><div class="wc-sub">Prepare files in their folder and validate all uploaded data before review and approval.</div><div class="dropzone"><i class="bi bi-cloud-arrow-up"></i><div class="dz-title">Drag & drop files here, or click to browse</div><div class="dz-sub">UI preview only &mdash; files are not saved</div></div>@foreach($folders as [$name,$detail])<div class="checklist-row"><div class="ci-icon"><i class="bi bi-file-earmark"></i></div><div class="flex-grow-1"><div class="ci-name">{{ $loop->iteration }}. {{ $name }}</div><div class="ci-meta">{{ $detail }}</div></div><span class="badge-status pending">Pending</span><button type="button" class="btn btn-sm btn-outline-navy py-0 px-2">Upload</button></div>@endforeach
@elseif($step===6)<h4>Review, Approve & Generate Reports</h4><div class="wc-sub">Review the complete PPT document set, approve it, then generate reports and archive the final records.</div><div class="row g-3"><div class="col-md-4"><div class="folder-tile"><div class="fico"><i class="fa fa-check"></i></div><div class="ftitle">Review & Approve</div><div class="fmeta">Approve verified documents</div><span class="badge-status verified">Ready</span></div></div><div class="col-md-4"><div class="folder-tile"><div class="fico"><i class="fa fa-chart-bar"></i></div><div class="ftitle">Generate Reports</div><div class="fmeta">View / download reports</div><span class="badge-status pending">Pending</span></div></div><div class="col-md-4"><div class="folder-tile"><div class="fico"><i class="fa fa-archive"></i></div><div class="ftitle">Archive & Backup</div><div class="fmeta">Archive final project data</div><span class="badge-status pending">Pending</span></div></div></div><div class="card-panel mt-4 mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">PPT Department UI workflow completed.</span></div>
@elseif($step===7)
<h4>Data Preview</h4><div class="wc-sub">Review PPT Department data before final submission.</div>
<div class="card-panel mt-4 mb-4" style="background:var(--navy-soft); border:none;">
  <h6 style="color:var(--navy); font-weight:600; margin-bottom: 12px;"><i class="bi bi-person-lines-fill me-2"></i>Project Summary</h6>
  <div class="row g-2" style="font-size: 0.85rem;">
    <div class="col-md-4"><span class="text-muted">Client Name:</span> <br><b>Applicant name</b></div>
    <div class="col-md-4"><span class="text-muted">District:</span> <br><b>Coimbatore</b></div>
    <div class="col-md-4"><span class="text-muted">Mineral:</span> <br><b>Rough Stone</b></div>
    <div class="col-md-12 mt-2"><span class="text-muted">Folders & Documents:</span> <br><span class="badge bg-success">Approved</span></div>
  </div>
</div>
<div class="card-panel mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Please confirm to finalize the PPT Department process.</span></div>
@endif
<div class="wizard-actions"><a href="{{ $step === 1 ? route('ppt-department.index') : route('ppt-department.step', $step - 1) }}" class="btn btn-outline-navy btn-sm"><i class="bi bi-arrow-left"></i> {{ $step === 1 ? 'Cancel' : 'Back' }}</a>@can('ppt.create')<a href="{{ $step === 7 ? route('ppt-department.index') : route('ppt-department.step', $step + 1) }}" class="btn {{ $step === 7 ? 'btn-green' : 'btn-navy' }} px-4">{{ $step === 7 ? 'Finish Process' : 'Save & Continue' }} <i class="bi bi-arrow-right"></i></a>@endcan</div></div></div></div></div>

@endsection

