@extends('layouts.app')
@section('title', 'Environment Clearance B2 Applications')
@section('main_content')
<div class="content-body default-height"><div class="container-fluid">
  <div class="row page-titles"><div class="col-lg-6"><ol class="breadcrumb"><li class="breadcrumb-item active"><a href="javascript:void(0)">Environment Clearance — B2</a></li></ol></div><div class="col-lg-6 text-end"><a href="{{ route('environment-b2.step', 1) }}" class="btn btn-rounded btn-info"><span class="btn-icon-start text-info"><i class="fa fa-plus color-info"></i></span>New B2 Application</a></div></div>
  <div class="row">
    <div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-primary text-primary"><i class="fa fa-folder-open fa-2x"></i></span><div class="media-body"><p class="mb-1">Total B2 Applications</p><h4 class="mb-0">24</h4></div></div></div></div></div>
    <div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-warning text-warning"><i class="fa fa-hourglass-half fa-2x"></i></span><div class="media-body"><p class="mb-1">Under Validation</p><h4 class="mb-0">06</h4></div></div></div></div></div>
    <div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-success text-success"><i class="fa fa-check-circle fa-2x"></i></span><div class="media-body"><p class="mb-1">Approved</p><h4 class="mb-0">14</h4></div></div></div></div></div>
    <div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-danger text-danger"><i class="fa fa-archive fa-2x"></i></span><div class="media-body"><p class="mb-1">Archived</p><h4 class="mb-0">04</h4></div></div></div></div></div>
  </div>
  <div class="row"><div class="col-12"><div class="card"><div class="card-header"><h4 class="card-title mb-0">B2 Clearance Applications</h4></div><div class="card-body"><div class="table-responsive"><table id="example10" class="display" style="width:100%"><thead><tr><th>S No</th><th>Application No.</th><th>Client / Applicant</th><th>Project / Location</th><th>Category</th><th>Documents</th><th>Process Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>
    @php($applications=[['ECB2-2026-0014','M. Senthil Kumar','Black Granite Quarry · Salem','29 / 29','Approved','06 Aug 2026'],['ECB2-2026-0013','S. Priya','Rough Stone Quarry · Erode','27 / 29','Validation','05 Aug 2026'],['ECB2-2026-0012','K. Rajendran','Blue Metal Quarry · Madurai','29 / 29','Archived','02 Aug 2026'],['ECB2-2026-0011','V. Karthik','Gravel Quarry · Coimbatore','18 / 29','Document Preparation','01 Aug 2026']])
    @foreach($applications as [$number,$client,$project,$documents,$status,$updated])<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $number }}</strong></td><td>{{ $client }}</td><td>{{ $project }}</td><td><span class="badge badge-info">B2</span></td><td><a href="{{ route('environment-b2.step', 4) }}">{{ $documents }} files</a></td><td><span class="badge badge-{{ $status === 'Approved' ? 'success' : ($status === 'Archived' ? 'secondary' : ($status === 'Validation' ? 'warning' : 'primary')) }}">{{ $status }}</span></td><td>{{ $updated }}</td><td><a href="{{ route('environment-b2.step', $status === 'Document Preparation' ? 4 : 6) }}" class="btn btn-sm btn-primary">View</a></td></tr>@endforeach
  </tbody></table></div></div></div></div></div>
</div></div>
@endsection
