@extends('layouts.app')
@section('title', 'B2 Project — '.$project->project_code)
@section('main_content')
<div class="content-body default-height"><div class="container-fluid">
  <div class="d-flex justify-content-between align-items-start mb-4"><div><a href="{{ route('environment-b2.index') }}" class="text-muted small">← All B2 projects</a><h3 class="mb-1">{{ $project->project_name }}</h3><p class="mb-0 text-muted">{{ $project->project_code }} · {{ $project->client_name }} · B2 · {{ $project->location }}</p></div>@can('environment.b2.review')<form method="POST" action="{{ route('environment-b2.status', $project) }}" class="d-flex gap-2">@csrf<select name="status" class="form-select"><option value="draft" @selected($project->status==='draft')>Draft / upload</option><option value="validation" @selected($project->status==='validation')>Validate data</option><option value="approved" @selected($project->status==='approved')>Approve data</option><option value="reported" @selected($project->status==='reported')>Generate reports</option><option value="archived" @selected($project->status==='archived')>Archive & backup</option></select><button class="btn btn-primary">Move stage</button></form>@endcan</div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
  <div class="row g-3 mb-4"><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Checklist items</small><h3>{{ $summary['total'] }}</h3></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Uploaded / validation queue</small><h3>{{ $summary['uploaded'] }}</h3></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Approved</small><h3>{{ $summary['approved'] }}</h3></div></div></div></div>
  <div class="row"><div class="col-lg-8">
  @foreach($folders as $folder => $documents)<div class="card mb-3"><div class="card-header d-flex justify-content-between"><strong>{{ $loop->iteration }}. {{ $folder }}</strong><span class="text-muted">{{ $documents->where('status','approved')->count() }} / {{ $documents->count() }} approved</span></div><div class="table-responsive"><table class="table mb-0 align-middle"><thead><tr><th>Required document</th><th>Status</th><th>File</th><th class="text-end">Actions</th></tr></thead><tbody>@foreach($documents as $document)<tr><td><strong>{{ $document->document_name }}</strong>@if($document->description)<br><small>{{ $document->description }}</small>@endif @if($document->review_note)<br><small class="text-danger">Note: {{ $document->review_note }}</small>@endif</td><td><span class="badge badge-{{ $document->status === 'approved' ? 'success' : ($document->status === 'revision_required' ? 'danger' : ($document->status === 'pending' ? 'secondary' : 'warning')) }}">{{ str_replace('_',' ', ucfirst($document->status)) }}</span></td><td>@if($document->file_path)<a href="{{ route('environment-b2.documents.download', $document) }}">{{ $document->original_name }}</a><br><small>{{ optional($document->uploaded_at)->format('d M Y H:i') }}</small>@else <span class="text-muted">Not uploaded</span>@endif</td><td class="text-end">@can('environment.b2.upload')<button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#upload{{ $document->id }}">Upload</button>@endcan @can('environment.b2.review')@if($document->file_path)<button type="button" class="btn btn-sm btn-outline-success" data-bs-toggle="modal" data-bs-target="#review{{ $document->id }}">Review</button>@endif @endcan</td></tr>

  <div class="modal fade" id="upload{{ $document->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{ route('environment-b2.documents.upload', $document) }}">@csrf<div class="modal-header"><h5 class="modal-title">Upload: {{ $document->document_name }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input class="form-control" type="file" name="file" required accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip"><small class="text-muted">PDF, images, Office files or ZIP; maximum 10 MB.</small></div><div class="modal-footer"><button class="btn btn-primary">Upload</button></div></form></div></div>
  <div class="modal fade" id="review{{ $document->id }}" tabindex="-1"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('environment-b2.documents.review', $document) }}">@csrf<div class="modal-header"><h5 class="modal-title">Review: {{ $document->document_name }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Decision</label><select name="status" class="form-select"><option value="validated">Validated</option><option value="approved">Approved</option><option value="revision_required">Revision required</option></select><label class="form-label mt-3">Review note</label><textarea class="form-control" name="review_note" rows="3"></textarea></div><div class="modal-footer"><button class="btn btn-success">Save review</button></div></form></div></div>
  @endforeach</tbody></table></div></div>@endforeach
  </div><div class="col-lg-4"><div class="card"><div class="card-header"><strong>Process flow</strong></div><div class="card-body"><ol class="mb-0 ps-3"><li>Client / applicant</li><li>Sub-category B2</li><li>Environment Clearance — B2 folder</li><li>Document preparation</li><li>Upload & store data</li><li>Validate data</li><li>Approve data</li><li>Generate reports</li><li>Archive & backup</li></ol></div></div><div class="card mt-3"><div class="card-header"><strong>Activity log</strong></div><div class="card-body">@forelse($project->activities as $activity)<div class="mb-3"><strong>{{ $activity->action }}</strong><br><small class="text-muted">{{ $activity->details }} · {{ $activity->created_at->diffForHumans() }}</small></div>@empty <span class="text-muted">No activity yet.</span>@endforelse</div></div></div></div>
</div></div>
@endsection
