@extends('layouts.app')
@section('title', 'EC Certificate Issuance')
@section('main_content')
<div class="content-body default-height"><div class="container-fluid">
  <div class="row page-titles"><div class="col-lg-6"><ol class="breadcrumb"><li class="breadcrumb-item active"><a href="javascript:void(0)">EC Certificate Issuance</a></li></ol></div><div class="col-lg-6 text-end"><a href="{{ route('ec-certificate.step', 1) }}" class="btn btn-rounded btn-info"><span class="btn-icon-start text-info"><i class="fa fa-plus color-info"></i></span>Issue EC Certificate</a></div></div>
  <div class="row"><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-primary text-primary"><i class="fa fa-file-signature fa-2x"></i></span><div class="media-body"><p class="mb-1">EC Approved</p><h4 class="mb-0">18</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-warning text-warning"><i class="fa fa-download fa-2x"></i></span><div class="media-body"><p class="mb-1">Ready to Download</p><h4 class="mb-0">06</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-success text-success"><i class="fa fa-certificate fa-2x"></i></span><div class="media-body"><p class="mb-1">Certificates Issued</p><h4 class="mb-0">12</h4></div></div></div></div></div><div class="col-xl-3 col-lg-3 col-sm-6"><div class="widget-stat card"><div class="card-body p-4"><div class="media ai-icon"><span class="me-3 bgl-danger text-danger"><i class="fa fa-envelope fa-2x"></i></span><div class="media-body"><p class="mb-1">Communicated</p><h4 class="mb-0">11</h4></div></div></div></div></div></div>
  <div class="card"><div class="card-header"><h4 class="card-title mb-0">Environmental Clearance Certificates</h4></div><div class="card-body"><div class="table-responsive"><table id="example10" class="display" style="width:100%"><thead><tr><th>S No</th><th>EC Reference No.</th><th>Applicant</th><th>Project</th><th>Parivesh Status</th><th>Certificate</th><th>Communication</th><th>Updated</th><th>Actions</th></tr></thead><tbody>@php($records=[['EC-2026-0082','M. Senthil Kumar','Black Granite Quarry','Approved','Issued','Sent','06 Aug 2026'],['EC-2026-0081','S. Priya','Rough Stone Quarry','Approved','Ready to download','Pending','05 Aug 2026'],['EC-2026-0080','K. Rajendran','Blue Metal Quarry','Approved','Issued','Sent','02 Aug 2026'],['EC-2026-0079','V. Karthik','Gravel Quarry','Under review','Not available','Pending','01 Aug 2026']])@foreach($records as [$reference,$applicant,$project,$parivesh,$certificate,$communication,$updated])<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $reference }}</strong></td><td>{{ $applicant }}</td><td>{{ $project }}</td><td><span class="badge badge-{{ $parivesh === 'Approved' ? 'success' : 'warning' }}">{{ $parivesh }}</span></td><td><span class="badge badge-{{ $certificate === 'Issued' ? 'success' : 'primary' }}">{{ $certificate }}</span></td><td><span class="badge badge-{{ $communication === 'Sent' ? 'success' : 'secondary' }}">{{ $communication }}</span></td><td>{{ $updated }}</td><td><a href="{{ route('ec-certificate.step', $certificate === 'Issued' ? 5 : 1) }}" class="btn btn-sm btn-primary">View</a></td></tr>@endforeach</tbody></table></div></div></div>
</div></div>
@endsection
