@extends('layouts.app')
@section('title', 'EC Certificate Issuance')
@section('main_content')
<link href="{{ asset('css/style1.css') }}" rel="stylesheet">
@php($labels=['Parivesh Approval','Download EC','View / Print','Store Documents','Communicate', 'Preview'])
@php($details=[['EC Approved on Parivesh Portal','Confirm that the environmental clearance is approved in the Parivesh portal before issuing the certificate.','fa-check-circle'],['Download EC Certificate','Download the approved EC certificate from the Parivesh portal.','fa-download'],['View / Print EC Certificate','Check the certificate details and prepare a printed copy where required.','fa-print'],['Store EC Certificate & Documents','Store the EC certificate together with the final project documents.','fa-folder-open'],['Communicate EC Grant / Rejection Letter','Send the certificate or grant/rejection communication to the applicant.','fa-envelope'],['Preview','Review issuance details','fa-eye']])
<div class="content-body default-height"><div class="container-fluid"><div class="wizard-wrap"><div class="step-progress">@foreach($labels as $number => $label)<div class="sp-step {{ $number + 1 < $step ? 'done' : ($number + 1 === $step ? 'active' : '') }}"><div class="circ">@if($number + 1 < $step)<i class="bi bi-check-lg"></i>@else{{ $number + 1 }}@endif</div><div class="sp-label">{{ $label }}</div></div>@endforeach</div><div class="wizard-card"><div class="wc-eyebrow">EC Certificate Issuance &middot; Sub Process {{ $step }} of 6</div><h4>{{ $details[$step - 1][0] }}</h4><div class="wc-sub">{{ $details[$step - 1][1] }}</div>
@if($step===1)<div class="row g-3"><div class="col-md-6"><label class="form-label">EC Application Reference *</label><input class="form-control" placeholder="e.g. EC-2026-0082"></div><div class="col-md-6"><label class="form-label">Parivesh Application No. *</label><input class="form-control" placeholder="Parivesh reference number"></div><div class="col-md-6"><label class="form-label">Applicant Name *</label><input class="form-control" placeholder="Applicant name"></div><div class="col-md-6"><label class="form-label">Approval Date</label><input class="form-control" type="date"></div></div><div class="card-panel mt-4 mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Approval confirmed: continue to download the EC certificate.</span></div>
@elseif($step===2)<div class="dropzone"><i class="bi bi-cloud-arrow-down"></i><div class="dz-title">Download EC Certificate from Parivesh Portal</div><div class="dz-sub">Certificate PDF will be attached to the project record</div></div><div class="checklist-row mt-4"><div class="ci-icon"><i class="bi bi-file-earmark-pdf"></i></div><div class="flex-grow-1"><div class="ci-name">Environmental Clearance Certificate</div><div class="ci-meta">Awaiting download from Parivesh</div></div><span class="badge-status pending">Pending</span><button type="button" class="btn btn-sm btn-outline-navy py-0 px-2">Download</button></div>
@elseif($step===3)<div class="card-panel" style="min-height:230px;background:#f8fafc"><div class="text-center pt-4"><i class="fa fa-file-certificate" style="font-size:4rem;color:var(--navy)"></i><h5 class="mt-3">Environmental Clearance Certificate</h5><p class="text-muted small">Preview certificate details before printing.</p><button type="button" class="btn btn-outline-navy btn-sm"><i class="fa fa-print"></i> View / Print Certificate</button></div></div>
@elseif($step===4)<div class="row g-3"><div class="col-md-6"><div class="folder-tile"><div class="fico"><i class="fa fa-certificate"></i></div><div class="ftitle">EC Certificate</div><div class="fmeta">Store signed / approved certificate PDF</div><span class="badge-status uploaded">Ready to store</span></div></div><div class="col-md-6"><div class="folder-tile"><div class="fico"><i class="fa fa-folder-open"></i></div><div class="ftitle">Final Project Documents</div><div class="fmeta">Archive all associated EC documents</div><span class="badge-status uploaded">Ready to store</span></div></div></div>
@elseif($step===5)<div class="row g-3"><div class="col-md-6"><label class="form-label">Communication Type</label><select class="form-select"><option>EC Grant Letter</option><option>EC Rejection Letter</option></select></div><div class="col-md-6"><label class="form-label">Recipient Email</label><input class="form-control" placeholder="applicant@example.com"></div><div class="col-12"><label class="form-label">Communication Note</label><textarea class="form-control" rows="4" placeholder="Certificate communication details"></textarea></div></div><div class="card-panel mt-4 mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Output: Environmental Clearance Certificate Issued.</span></div>
@elseif($step===6)
<div class="card-panel mt-4 mb-4" style="background:var(--navy-soft); border:none;">
  <h6 style="color:var(--navy); font-weight:600; margin-bottom: 12px;"><i class="bi bi-card-checklist me-2"></i>EC Issuance Summary</h6>
  <div class="row g-2" style="font-size: 0.85rem;">
    <div class="col-md-6"><span class="text-muted">Applicant Name:</span> <br><b>Applicant name</b></div>
    <div class="col-md-6"><span class="text-muted">EC App Ref:</span> <br><b>EC-2026-0082</b></div>
    <div class="col-md-6 mt-2"><span class="text-muted">Communication Type:</span> <br><b>EC Grant Letter</b></div>
    <div class="col-md-6 mt-2"><span class="text-muted">Status:</span> <br><span class="badge bg-success">Documents Stored</span></div>
  </div>
</div>
<div class="card-panel mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Please confirm to finalize the EC Certificate Issuance process.</span></div>
@endif
<div class="wizard-actions"><a href="{{ $step === 1 ? route('ec-certificate.index') : route('ec-certificate.step', $step - 1) }}" class="btn btn-outline-navy btn-sm"><i class="bi bi-arrow-left"></i> {{ $step === 1 ? 'Cancel' : 'Back' }}</a>@can('environment.create')<a href="{{ $step === 6 ? route('ec-certificate.index') : route('ec-certificate.step', $step + 1) }}" class="btn {{ $step === 6 ? 'btn-green' : 'btn-navy' }} px-4">{{ $step === 6 ? 'Finish Process' : 'Save & Continue' }} <i class="bi bi-arrow-right"></i></a>@endcan</div></div></div></div></div>

@endsection
