@extends('layouts.app')
@section('title', 'Drone Survey Workflow')
@section('main_content')
<link href="{{ asset('css/style1.css') }}" rel="stylesheet">
@php($labels=['Survey Request','Data Acquisition','Data Processing','Deliverables','GTMS Upload', 'Preview'])
@php($steps=[['Drone Survey Request',['Request Letter','Lease Area Details','Approved Mining Plan','EC Copy'],'fa-file-alt'],['Drone Data Acquisition',['Drone Flying','Aerial Photography','Image Capture','Video Recording'],'fa-paper-plane'],['Data Processing',['Image Stitching','Orthomosaic Map','Contour Generation','3D Model (if required)'],'fa-cogs'],['Drone Survey Deliverables',['Orthomosaic Map','Contour Map (DSM / DTM)','3D Model / Point Cloud','Survey Report'],'fa-map'],['Report Upload in GTMS Portal',['Upload final drone survey report and deliverables'],'fa-cloud-upload-alt'],['Preview',['Review submitted data','Confirm completion'],'fa-eye']])
<div class="content-body default-height"><div class="container-fluid"><div class="wizard-wrap"><div class="step-progress">@foreach($labels as $number=>$label)<div class="sp-step {{ $number+1<$step?'done':($number+1===$step?'active':'') }}"><div class="circ">@if($number+1<$step)<i class="bi bi-check-lg"></i>@else{{ $number+1 }}@endif</div><div class="sp-label">{{ $label }}</div></div>@endforeach</div><div class="wizard-card"><div class="wc-eyebrow">Drone Department &mdash; Survey &middot; Sub Process {{ $step }} of 6</div><h4>{{ $steps[$step-1][0] }}</h4><div class="wc-sub">Complete the drone survey activities in this stage before moving to the next step.</div>
@if($step===1)<div class="row g-3"><div class="col-md-6"><label class="form-label">Drone Survey Request No. *</label><input class="form-control" placeholder="DRN-2026-0026"></div><div class="col-md-6"><label class="form-label">Client / Applicant *</label><input class="form-control" placeholder="Applicant name"></div><div class="col-md-6"><label class="form-label">Lease Area</label><input class="form-control" placeholder="Area in hectares"></div><div class="col-md-6"><label class="form-label">Location</label><input class="form-control" placeholder="District / village"></div></div>@endif
@if($step===2)<div class="row g-3"><div class="col-md-6"><label class="form-label">Flight Date</label><input class="form-control" type="date"></div><div class="col-md-6"><label class="form-label">Drone / Pilot Details</label><input class="form-control" placeholder="Drone and pilot name"></div></div><div class="card-panel mt-4 mb-0" style="background:var(--navy-soft);border:none"><i class="bi bi-camera-video"></i> <span style="font-size:.78rem">Capture aerial photographs, images and video recordings during the survey.</span></div>@endif
@if($step===3)<div class="dropzone"><i class="bi bi-image"></i><div class="dz-title">Process drone images and captured data</div><div class="dz-sub">Create stitched imagery, orthomosaic map and contours</div></div>@endif
@if($step===4)<div class="card-panel" style="min-height:190px;background:#f8fafc"><div class="text-center pt-3"><i class="fa fa-map-marked-alt" style="font-size:3.5rem;color:var(--navy)"></i><h5 class="mt-3">Drone Survey Deliverables</h5><p class="text-muted small">Orthomosaic, contour map, 3D model / point cloud and survey report.</p><button type="button" class="btn btn-outline-navy btn-sm">View Deliverables</button></div></div>@endif
@if($step===5)<div class="card-panel" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Output: Drone Survey Completed and deliverables uploaded in GTMS portal.</span></div>@endif
@if($step===6)
<div class="card-panel mt-4 mb-4" style="background:var(--navy-soft); border:none;">
  <h6 style="color:var(--navy); font-weight:600; margin-bottom: 12px;"><i class="bi bi-card-checklist me-2"></i>Drone Survey Summary</h6>
  <div class="row g-2" style="font-size: 0.85rem;">
    <div class="col-md-6"><span class="text-muted">Client / Applicant:</span> <br><b>Applicant name</b></div>
    <div class="col-md-6"><span class="text-muted">Survey Request No:</span> <br><b>DRN-2026-0026</b></div>
    <div class="col-md-6 mt-2"><span class="text-muted">Lease Area:</span> <br><b>Area in hectares</b></div>
    <div class="col-md-6 mt-2"><span class="text-muted">Status:</span> <br><span class="badge bg-success">All Stages Completed</span></div>
  </div>
</div>
<div class="card-panel mb-0" style="background:var(--green-soft);border:none"><i class="bi bi-check-circle"></i> <span style="font-size:.78rem">Please confirm to finalize the Drone Survey process.</span></div>
@endif
<div class="mt-4">@foreach($steps[$step-1][1] as $item)<div class="checklist-row"><div class="ci-icon"><i class="bi bi-check-lg"></i></div><div class="flex-grow-1"><div class="ci-name">{{ $loop->iteration }}. {{ $item }}</div><div class="ci-meta">{{ $step<6?'To be completed':'Completed' }}</div></div><span class="badge-status {{ $step<6?'pending':'verified' }}">{{ $step<6?'Pending':'Completed' }}</span></div>@endforeach</div><div class="wizard-actions"><a href="{{ $step===1?route('drone-survey.index'):route('drone-survey.step',$step-1) }}" class="btn btn-outline-navy btn-sm"><i class="bi bi-arrow-left"></i> {{ $step===1?'Cancel':'Back' }}</a><a href="{{ $step===6?route('drone-survey.index'):route('drone-survey.step',$step+1) }}" class="btn {{ $step===6?'btn-green':'btn-navy' }} px-4">{{ $step===6?'Finish Process':'Save & Continue' }} <i class="bi bi-arrow-right"></i></a></div></div></div></div></div>
@endsection
